--- # Site configuration
entries:
    layout: base.twig

# Files to skip - list of preg expressions is expected
# I shouldnt have any of these files anyway...
# skip: [/\.swp$/, /\.bak$/, /.DS_Store/]
